name: flutter_support_cli
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: phamnhuvu <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  recase: ^2.0.1
  meta: ^1.1.7
  args: ^1.5.1
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0

executables:
  flusu: flutter_support_cli